maurice:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30  
  
  # Position Controllers ---------------------------------------
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 10.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 10.0, i: 0.0, d: 0.0,  i_clamp: 0.0}
