device: /dev/ttyACM0
frame_id: gps
rate: 4                     # in Hz
nav_rate: 4
usb:
  baudrate: 38400
  in: 5                    # RTCM 3
  out: 0                   # UBX
config_on_startup: false
